# Generated by Django 2.0.2 on 2018-12-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opencons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hyperlink', models.URLField()),
                ('title', models.CharField(max_length=300)),
            ],
        ),
    ]
