# Generated by Django 2.0.2 on 2018-12-26 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_consultations_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
